'use strict';

window.µConfig = {
  urls: {
    front: "https://www.varanida.com/",
    api: "https://api.varanida.com/"
  },
  aws: {
    identityPoolId: "us-east-1:95c6c669-64ea-43ca-baf6-414758edbf1e",
    region: 'us-east-1',
    kinesis: {
      apiVersion: '2013-12-02'
    }
  },
  rewards: {
    install: 50,
    referral: 20,
    bonusPercentageForData: [0,12,24,36]
  },
  minimalPasswordLength: 8,
  rewardedFilterLists: {
    "BGR: Bulgarian Adblock list": true,
    "CHN: EasyList China (中文)": true,
    "CHN: CJX's EasyList Lite": true,
    "CZE, SVK: EasyList Czech and Slovak": true,
    "DEU: EasyList Germany": true,
    "DNK: Schacks Adblock Plus liste": true,
    "EST: Eesti saitidele kohandatud filter": true,
    "FIN: Finnish Addition to Easylist": true,
    "FRA: EasyList Liste FR": true,
    "GRC: Greek AdBlock Filter": true,
    "HUN: hufilter": true,
    "IDN: ABPindo": true,
    "IRN: Adblock-Iran": true,
    "ISL: Icelandic ABP List": true,
    "ISR: EasyList Hebrew": true,
    "ITA: EasyList Italy": true,
    "ITA: ABP X Files": true,
    "JPN: ABP Japanese filters (日本用フィルタ)": true,
    "JPN: Adguard Japan Filter": true,
    "KOR: Korean Adblock List": true,
    "KOR: YousList": true,
    "LTU: Adblock Plus Lithuania": true,
    "LVA: Latvian List": true,
    "NLD: EasyList Dutch": true,
    "NOR: Dandelion Sprouts norske filtre": true,
    "POL: polskie filtry do Adblocka i uBlocka": true,
    "ROU: Romanian Ad (ROad) Block List Light": true,
    "RUS: RU AdList": true,
    "RUS: Adguard Russian Filter": true,
    "SVN: Slovenian List": true,
    "SWE: Frellwit's Swedish Filter": true,
    "TUR: Adguard Turkish Filter": true,
    "VIE: ABPVN List": true,
    "Adguard’s Annoyance List": false,
    "Adguard Base Filters": true,
    "Adguard Mobile Filters": true,
    "Adguard Spyware Filters": false,
    "ara: Liste AR": true,
    "Adblock Warning Removal List": false,
    "Malvertising filter list by Disconnect": false,
    "Dan Pollock’s hosts file": false,
    "EasyList": true,
    "EasyPrivacy": false,
    "Fanboy’s Annoyance List": false,
    "Fanboy’s Cookiemonster List": false,
    "Fanboy’s Enhanced Tracking List": false,
    "Fanboy’s Social Blocking List": false,
    "Fanboy’s Anti-Thirdparty Social (see warning inside list)": false,
    "hpHosts’ Ad and tracking servers": false,
    "Malware Domain List": false,
    "Malware domains": false,
    "MVPS HOSTS": false,
    "Peter Lowe’s Ad and tracking server list": true,
    "spa: EasyList Spanish": true,
    "spa, por: Adguard Spanish/Portuguese": true,
    "Spam404": false,
    "uBlock filters – Resource abuse": true,
    "uBlock filters – Annoyances": false,
    "uBlock filters – Badware risks": false,
    "uBlock filters – Experimental": false,
    "uBlock filters": true,
    "uBlock filters – Privacy": false,
    "uBlock filters – Unbreak": false,
    "Mes filtres": false
  }
};
